# This file is a template, and might need editing before it works on your project.
# see https://docs.gitlab.com/ee/ci/yaml/README.html for all available options

# you can delete this line if you're not using Docker

variables:
  DOCKER_VERSION: 18.09.7
  DOCKER_BUILD_OPTS: ""
  KANIKO_EXECUTOR_VERSION: "debug-v0.14.0"
  KANIKO_WORK_DIR: "$CI_PROJECT_DIR"
  ## Enable to override the default docker image name
  TARGET_REGISTRY_IMAGE: $CI_REGISTRY_IMAGE
  DEV_IMAGE_TAG: "$CI_COMMIT_TAG"
  # Docker images used in jobs
  BUSYBOX_IMAGE: busybox:1.31.0
  SONAR_SCANNER_IMAGE: gitlab.thalesdigital.io:5005/prs-sdp/tooling/sonar-scanner:1.1.0
  TRIGGER_DEPLOYMENT_IMAGE: curlimages/curl:7.72.0
  # Checkmarx treesholds
  CHECKMARX_SAST_LOW: 50
  CHECKMARX_SAST_MEDIUM: 10
  CHECKMARX_SAST_HIGH: 1
  CHECKMARX_RUN_OPT: ""

.default-job-config:
  tags:
    - autoscale
  cache: {}
  artifacts:
    expire_in: 4 hour
  retry:
    max: 2
    when:
      - runner_system_failure
      - unknown_failure

image: busybox:latest

stages:
  - check
  - build
  - dockerize
license-check:
  stage: check
  extends: .default-job-config
  image: $BUSYBOX_IMAGE
  script:
    # Check that license file exists
    - "[ -f LICENSE ] || { echo 'LICENSE file not found'; exit 1; }"
    # Check that license file is up to date with commit date (in order to be able to build old versions)
    # - grep -q ".*Copyright.*`git show -s --format=%ci $CI_COMMIT_SHA |cut -b1-4`.*" LICENSE || { echo 'Dates in LICENSE file are outdated'; exit 1; }
    - cat LICENSE
  dependencies: []
  allow_failure: true
build:
  stage: build
  extends: .default-job-config
  artifacts:
    untracked: true
  image: python
  script:
    - python setup.py build
# Build Docker images using Kaniko (does not need access to runner's Docker)
dev-docker-image-kaniko:
  extends: .default-job-config
  stage: dockerize
  dependencies:
    - build
  image:
    name: gcr.io/kaniko-project/executor:$KANIKO_EXECUTOR_VERSION
    entrypoint: [""]
  script:
    - ls build/lib/medusa
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_JOB_TOKEN\"}}}" > /kaniko/.docker/config.json
    - /kaniko/executor --context $KANIKO_WORK_DIR --dockerfile $KANIKO_WORK_DIR/Dockerfile --destination $TARGET_REGISTRY_IMAGE:$DEV_IMAGE_TAG --build-arg CI_COMMIT_SHA=$CI_COMMIT_SHA --build-arg CI_COMMIT_TAG=$DEV_IMAGE_TAG $DOCKER_BUILD_OPTS


